#!/bin/bash

sudo cp /usr/local/bin/my* ~/dev/collection/linuxessentials/scripts/global/

sudo cp ~/.latexmkrc ~/dev/collection/latex-r/docs/dots/

sudo cp ~/.emacs.d/init.el ~/dev/collection/linuxessentials/docs/dots/
