#!/bin/bash
texFile="$1"

filename="${texFile%.*}"
filename+=".sagetex.sage"
echo $filename
echo $texFile

if [ -z "$texFile"   ]
then
	echo "Using main.tex" 
	texFile="main.tex" 
fi


latexmk "$texFile" -pdf

# if its a sage -> compile that 
if [ -f "build_latex/$filename" ]; then
     cd build_latex && pwd && sage "$filename" && cd .. && latexmk "$texFile" -g -pdf 
else
    echo "not a sage"
fi
latexmk -c

