#!/bin/bash
texFile="$1"

filename="${texFile%.*}"
filename+=".sagetex.sage"
echo $filename
echo $texFile

if [ -z "$texFile"   ]
then
	echo "Using main.tex" 
	texFile="main.tex" 
fi
pwd
latexmk "$texFile" -pdf && cd build_latex && pwd && sage "$filename" && cd .. && latexmk "$texFile" -g -pdf
latexmk -c

